protected/models/Credential.php
<?php

/**
 * This is the model class for table "credentials".
 *
 * The followings are the available columns in table 'credentials':
 * @property integer $id
 * @property integer $user_id
 * @property integer $image_id
 * @property string $value
 * @property integer $type
 * @property string $md5
 * @property string $sha256
 *
 * The followings are the available model relations:
 * @property User $user
 * @property Image $image
 */
class Credential extends CActiveRecord
{
	const TYPE_EMAIL = 1;
	const TYPE_URL   = 2;

	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Credential the static model class
	 */
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'credentials';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('user_id, value, type', 'required'),
			array('user_id, type', 'numerical', 'integerOnly' => true),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, user_id, value, type', 'safe', 'on' => 'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user'  => array(self::BELONGS_TO, 'User', 'user_id'),
			'image' => array(self::BELONGS_TO, 'Image', 'image_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id'      => 'ID',
			'user_id' => 'User',
			'value'   => 'Value',
			'type'    => 'Type',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('type', $this->type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}

protected/controllers/AvatarController.php
<?php

class AvatarController extends Controller
{
	public function actionAvatar($hash,
	                             $size = null,          $s = null,
	                             $default = null,       $d = null,
	                             $forcedefault = null,  $f = null
	) {
		$size = intval($size) ?: intval($s) ?: 80;
		$default = $default ?: $d;
		$forcedefault = ($forcedefault ?: $f);
		$forcedefault = ($forcedefault == '1' || $forcedefault == 'y');

		$type = null;

		if (strlen($hash) === 32)
		{
			$type = 'md5';
		}
		elseif (strlen($hash) === 64)
		{
			$type = 'sha256';
		}

		if ($type && $forcedefault === false)
		{
			/** @var Credential $cred */
			$cred = Credential::model()->findByAttributes([$type => $hash]);

			if ($cred && $cred->image_id)
			{
				$file = \application\helpers\PathHelper::getImageFilePath($cred->image->file);
				$avatar = \application\helpers\PathHelper::getResizeFilePath($cred->image->hash, $size);

				if (is_file($avatar) === false)
				{
					if (is_file($file) === false)
					{
						throw new CHttpException('500', 'Incorrect image');
					}

					\application\helpers\ImageResizer::Resize($file, $avatar, $size);
				}

				// enable cache for 3 days
				header('Cache: public');
				header('Expires: '. date('r', strtotime('+3 days')));
				header('Content-type: image/png');
				readfile($avatar);

				Yii::app()->end();
			}
		}

		$query = [
			's' => $size,
		];

		if ($default)
		{
			$query['d'] = $default;
		}

		if ($forcedefault)
		{
			$query['f'] = 'y';
			$hash = md5('test@example.com');
		}

		$ssl = !empty($_SERVER['HTTPS']);

		$link = $ssl ? 'http://cdn.libravatar.org' : 'https://seccdn.libravatar.org';
		$link.= '/avatar/'. $hash .'?'. http_build_query($query);

		$this->redirect($link, true);
	}
}

protected/controllers/CredentialsController.php
<?php

class CredentialsController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout = '//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => array('index', 'view', 'create', 'update', 'associate', 'delete'),
				'users'   => array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => array('admin'),
				'users'   => array('admin'),
			),
			array('deny', // deny all users
				'users' => array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view', array(
			'model' => $this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new Credential;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Credential']))
		{
			$model->attributes = $_POST['Credential'];

			$model->user_id = Yii::app()->user->model->id;

			$model->sha256 = hash('sha256', $model->value);

			if ($model->type == Credential::TYPE_EMAIL)
			{
				$model->md5 = md5($model->value);
			}

			if ($model->save())
			{
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array(
			'model' => $model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Credential']))
		{
			$model->attributes = $_POST['Credential'];

			$model->sha256 = hash('sha256', $model->value);

			if ($model->type == Credential::TYPE_EMAIL)
			{
				$model->md5 = md5($model->value);
			}

			if ($model->save())
			{
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
			'model' => $model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax']))
		{
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Credential');
		$dataProvider->setSort(['defaultOrder' => ['value' => CSort::SORT_ASC]]);
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new Credential('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['Credential']))
		{
			$model->attributes = $_GET['Credential'];
		}

		$this->render('admin', array(
			'model' => $model,
		));
	}

	public function actionAssociate($c, $i = null)
	{
		$cred = $this->loadModel($c);

		if ($i)
		{
			/** @var Image $img */
			$img = Image::model()->findByPk($i);
			if ($img === null || $img->user_id !== $cred->user_id)
			{
				throw new CHttpException(404, 'The requested page does not exist.');
			}

			$cred->image_id = $img->id;

			if ($cred->save())
			{
				$this->redirect(['index']);
			}
		}

		$images = Image::model()->findAllByAttributes(['user_id' => $cred->user_id]);

		$this->render('associate', array(
			'cred'   => $cred,
			'images' => $images,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Credential the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model = Credential::model()->findByPk($id);
		if ($model === null)
		{
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Credential $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'credential-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/credentials/_form.php
<?php
/* @var $this CredentialsController */
/* @var $model Credential */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'credential-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'value'); ?>
		<?php echo $form->textField($model,'value'); ?>
		<?php echo $form->error($model,'value'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'type'); ?>
		<?php echo $form->dropDownList($model,'type', [
			Credential::TYPE_EMAIL => 'Email',
			Credential::TYPE_URL => 'OpenID',
		]); ?>
		<?php echo $form->error($model,'type'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/credentials/_search.php
<?php
/* @var $this CredentialsController */
/* @var $model Credential */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'value'); ?>
		<?php echo $form->textField($model,'value'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'type'); ?>
		<?php echo $form->textField($model,'type'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'image_id'); ?>
		<?php echo $form->textField($model,'image_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'md5'); ?>
		<?php echo $form->textField($model,'md5',array('size'=>32,'maxlength'=>32)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'sha256'); ?>
		<?php echo $form->textField($model,'sha256',array('size'=>40,'maxlength'=>40)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/credentials/_view.php
<?php
/* @var $this CredentialsController */
/* @var $data Credential */
?>

<div class="view">

	<?php if ($data->type === Credential::TYPE_EMAIL): ?>
		<b>Email:</b>
	<?php else: ?>
		<b>OpenID:</b>
	<?php endif ?>
	<?= CHtml::link(CHtml::encode($data->value), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('image_id')); ?>:</b>
	<?= CHtml::link($data->image_id ? $data->image->imgThumbnailCode : 'No Image', ['credentials/associate', 'c' => $data->id]); ?>
	<br />

</div>

protected/views/credentials/admin.php
<?php
/* @var $this CredentialsController */
/* @var $model Credential */

$this->breadcrumbs=array(
	'Credentials'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Credential', 'url'=>array('index')),
	array('label'=>'Create Credential', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#credential-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Credentials</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'credential-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'user_id',
		'value',
		'type',
		'image_id',
		'md5',
		/*
		'sha256',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/credentials/associate.php
<?php
/**
 * @var Credential $cred
 * @var Image[] $images
 */
?>

<div>
	Set image for <?= $cred->type === Credential::TYPE_EMAIL ? 'Email' : 'OpenID' ?> <?= $cred->value ?>
</div>

<div>
	<?php foreach ($images as $i): ?>
		<div style="float:left; padding: ">
			<?= CHtml::link($i->imgThumbnailCode, ['credentials/associate', 'c' => $cred->id, 'i' => $i->id]) ?>
		</div>
	<?php endforeach ?>
</div>

protected/views/credentials/create.php
<?php
/* @var $this CredentialsController */
/* @var $model Credential */

$this->breadcrumbs=array(
	'Credentials'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Credential', 'url'=>array('index')),
	array('label'=>'Manage Credential', 'url'=>array('admin')),
);
?>

<h1>Create Credential</h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/credentials/index.php
<?php
/* @var $this CredentialsController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Credentials',
);

$this->menu=array(
	array('label'=>'Create Credential', 'url'=>array('create')),
	array('label'=>'Manage Credential', 'url'=>array('admin')),
);
?>

<h1>Credentials</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/credentials/update.php
<?php
/* @var $this CredentialsController */
/* @var $model Credential */

$this->breadcrumbs=array(
	'Credentials'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Credential', 'url'=>array('index')),
	array('label'=>'Create Credential', 'url'=>array('create')),
	array('label'=>'View Credential', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Credential', 'url'=>array('admin')),
);
?>

<h1>Update Credential <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/credentials/view.php
<?php
/* @var $this CredentialsController */
/* @var $model Credential */

$this->breadcrumbs=array(
	'Credentials'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Credential', 'url'=>array('index')),
	array('label'=>'Create Credential', 'url'=>array('create')),
	array('label'=>'Update Credential', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Credential', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Credential', 'url'=>array('admin')),
);
?>

<h1>View Credential #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'user_id',
		'value',
		'type',
		'image_id',
		'md5',
		'sha256',
	),
)); ?>

<?= CHtml::image(Yii::app()->createUrl('avatar/avatar', ['hash' => $model->sha256, 'size' => 32])) ?>
<?= CHtml::image(Yii::app()->createUrl('avatar/avatar', ['hash' => $model->sha256, 'size' => 80])) ?>
<?= CHtml::image(Yii::app()->createUrl('avatar/avatar', ['hash' => $model->sha256, 'size' => 150])) ?>