protected/models/Image.php
<?php

/**
 * This is the model class for table "images".
 *
 * The followings are the available columns in table 'images':
 * @property integer $id
 * @property integer $user_id
 * @property string $hash
 * @property string $file
 *
 * @property string $imgThumbnailCode
 *
 * The followings are the available model relations:
 * @property Credential[] $credentials
 * @property User $user
 */
class Image extends CActiveRecord
{
	/**
	 * @var CUploadedFile
	 */
	public $image; // file for upload

	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Image the static model class
	 */
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'images';
	}

	public function getImgThumbnailCode()
	{
		return CHtml::image(Yii::app()->createUrl('images/thumbnail', ['hash' => $this->hash]));
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return [
			['user_id, hash, file, image', 'required'],
			['user_id', 'numerical', 'integerOnly' => true],
			['image', 'file', 'types' => 'jpg, gif, png, jpeg'],
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			['id, user_id, hash, file', 'safe', 'on' => 'search'],
		];
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'credentials' => array(self::HAS_MANY, 'Credential', 'image_id'),
			'user'        => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id'      => 'ID',
			'user_id' => 'User',
			'hash'    => 'Hash',
			'file'    => 'File',
		);
	}

	public function delete()
	{
		foreach ($this->credentials as $cred)
		{
			$cred->image_id = null;
			$cred->save();
		}

		if ($this->hash)
		{
			if (is_dir($dir = \application\helpers\PathHelper::getResizesDirPath($this->hash)))
			{
				$iter = new DirectoryIterator($dir);

				foreach ($iter as $file) /** @var SplFileInfo $file */
				{
					if ($file->isFile())
					{
						unlink($file->getPathname());
					}
				}

				rmdir($dir);
			}
		}

		if ($this->file)
		{
			if (is_file($thumb = \application\helpers\PathHelper::getThumbnailFilePath($this->file)))
			{
				unlink($thumb);
			}

			if (is_file($file = \application\helpers\PathHelper::getImageFilePath($this->file)))
			{
				unlink($file);
			}
		}

		parent::delete();
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('hash', $this->hash, true);
		$criteria->compare('file', $this->file, true);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}
}

protected/controllers/ImagesController.php
<?php

/**
 * Work with images for the UI
 * (see AvatarController for the API)
 */
class ImagesController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout = '//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return [
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		];
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			['allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions' => ['index', 'view', 'image', 'thumbnail', 'create', 'update', 'delete'],
				'users'   => ['@'],
			],
			['allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions' => ['admin'],
				'users'   => ['admin'],
			],
			['deny', // deny all users
				'users' => ['*'],
			],
		];
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view', [
			'model' => $this->loadModel($id),
		]);
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model = new Image;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Image']))
		{
			$model->attributes = $_POST['Image'];
			$model->image      = CUploadedFile::getInstance($model, 'image');

			$model->hash    = hash('sha256', time() . $model->image->name . $model->image->size);
			$model->file    = $model->hash . '.' . $model->image->extensionName;
			$model->user_id = Yii::app()->user->model->id;

			if ($model->save())
			{
				$model->image->saveAs(\application\helpers\PathHelper::getImageFilePath($model->file));
				$this->redirect(['view', 'id' => $model->id]);
			}
		}

		$this->render('create', [
			'model' => $model,
		]);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model = $this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if (isset($_POST['Image']))
		{
			$model->attributes = $_POST['Image'];
			if ($model->save())
			{
				$this->redirect(['view', 'id' => $model->id]);
			}
		}

		$this->render('update', [
			'model' => $model,
		]);
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if (!isset($_GET['ajax']))
		{
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : ['index']);
		}
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider = new CActiveDataProvider('Image');
		$dataProvider->setPagination([
			'pageSize' => 60,
		]);
		$this->render('index', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model = new Image('search');
		$model->unsetAttributes(); // clear any default values
		if (isset($_GET['Image']))
		{
			$model->attributes = $_GET['Image'];
		}

		$this->render('admin', [
			'model' => $model,
		]);
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Image the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model = Image::model()->findByPk($id);
		if ($model === null)
		{
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Image $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'image-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	public function actionImage($hash)
	{
		/** @var Image $img */
		$img = Image::model()->findByAttributes(['hash' => $hash]);

		if ($img === null)
		{
			throw new CHttpException('404', 'Image not found');
		}

		$file = \application\helpers\PathHelper::getImageFilePath($img->file);

		if (is_file($file) === false)
		{
			throw new CHttpException('500', 'Incorrect image');
		}

		header('Content-type: image');

		readfile($file);

		Yii::app()->end();
	}

	public function actionThumbnail($hash)
	{
		/** @var Image $img */
		$img = Image::model()->findByAttributes(['hash' => $hash]);

		if ($img === null)
		{
			throw new CHttpException('404', 'Image not found');
		}

		$file  = \application\helpers\PathHelper::getImageFilePath($img->file);
		$thumb = \application\helpers\PathHelper::getThumbnailFilePath($img->file);

		if (is_file($thumb) === false)
		{
			if (is_file($file) === false)
			{
				throw new CHttpException('500', 'Incorrect image');
			}

			\application\helpers\ImageResizer::Resize($file, $thumb, 80);
		}

		header('Expires: '. date('r', strtotime('+3 days')));
		header('Content-type: image/png');
		readfile($thumb);

		Yii::app()->end();
	}
}

protected/views/images/_form.php
<?php
/* @var $this ImagesController */
/* @var $model Image */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', [
	'id'=>'image-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
	'htmlOptions' => ['enctype' => 'multipart/form-data'],
]); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'image'); ?>
		<?php echo $form->fileField($model,'image'); ?>
		<?php echo $form->error($model,'image'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/images/_search.php
<?php
/* @var $this ImagesController */
/* @var $model Image */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id'); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'user_id'); ?>
		<?php echo $form->textField($model,'user_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hash'); ?>
		<?php echo $form->textField($model,'hash'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'file'); ?>
		<?php echo $form->textField($model,'file'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/images/_view.php
<?php
/* @var $this ImagesController */
/* @var $data Image */
?>

<div class="view" style="display: inline-block;">

	<b>
	<?php echo CHtml::link(CHtml::image(Yii::app()->createUrl('images/thumbnail', ['hash' => $data->hash])), array('view', 'id'=>$data->id)); ?>
	<br />

</div>

protected/views/images/admin.php
<?php
/* @var $this ImagesController */
/* @var $model Image */

$this->breadcrumbs=array(
	'Images'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Image', 'url'=>array('index')),
	array('label'=>'Create Image', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#image-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Manage Images</h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link('Advanced Search','#',array('class'=>'search-button')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'image-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'user_id',
		'hash',
		'file',
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/images/create.php
<?php
/* @var $this ImagesController */
/* @var $model Image */

$this->breadcrumbs=array(
	'Images'=>array('index'),
	'Create',
);

$this->menu=array(
	array('label'=>'List Image', 'url'=>array('index')),
	array('label'=>'Manage Image', 'url'=>array('admin')),
);
?>

<h1>Create Image</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/images/index.php
<?php
/* @var $this ImagesController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Images',
);

$this->menu=array(
	array('label'=>'Create Image', 'url'=>array('create')),
	array('label'=>'Manage Image', 'url'=>array('admin')),
);
?>

<h1>Images</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/images/update.php
<?php
/* @var $this ImagesController */
/* @var $model Image */

$this->breadcrumbs=array(
	'Images'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Image', 'url'=>array('index')),
	array('label'=>'Create Image', 'url'=>array('create')),
	array('label'=>'View Image', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Image', 'url'=>array('admin')),
);
?>

<h1>Update Image <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/images/view.php
<?php
/* @var $this ImagesController */
/* @var $model Image */

$this->breadcrumbs=array(
	'Images'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Image', 'url'=>array('index')),
	array('label'=>'Create Image', 'url'=>array('create')),
	array('label'=>'Update Image', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Image', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Image', 'url'=>array('admin')),
);
?>

<h1>View Image #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'user_id',
		'hash',
		'file',
	),
)); ?>

<?= CHtml::image(Yii::app()->createUrl('images/image', ['hash' => $model->hash]), '', ['style' => 'max-width: 640px;']) ?>